#!/usr/bin/env bash
#
# Creates the Cloudflare Tunnel that makes this machine reachable, and writes the
# configuration the `cloudflared` container reads.
#
#   ./scripts/tunnel-setup.sh
#
# Run once. It is idempotent — running it again reuses the existing tunnel and
# re-asserts the DNS records.
#
# This takes the "locally-managed" route deliberately. The Zero Trust dashboard
# demands a payment method before it will show you the Tunnels page, even on the
# free plan; the CLI does not, and produces the same tunnel. Its only
# prerequisites are the two things already done: the domain is on Cloudflare and
# its nameservers point there.
#
# Afterwards there is no port to forward and no public IP anywhere in DNS, so
# this survives moving between wifi networks.
#
set -euo pipefail
# shellcheck source=scripts/_docker.sh
source "$(dirname -- "${BASH_SOURCE[0]}")/_docker.sh"

domain="$(sed -n 's/^DOMAIN=//p' .env | tail -1)"
domain="${domain:-canery.in}"
tunnel="${TUNNEL_NAME:-canery}"

# Every name nginx serves. Adding one here is not enough on its own — it also
# needs a server block in deploy/nginx/site-templates/.
hostnames=(
  "$domain"
  "www.$domain"
  "api.$domain"
  "pgadmin.$domain"
  "minioview.$domain"
  "minio.$domain"
  "portainer.$domain"
)

command -v cloudflared >/dev/null 2>&1 || fail "cloudflared is not installed. Install it, then re-run:

  curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o /tmp/cloudflared.deb
  sudo dpkg -i /tmp/cloudflared.deb"

# Authorises this machine against the zone and drops cert.pem in ~/.cloudflared.
# Opens a browser; pick canery.in on the page it lands on.
if [[ ! -f "$user_home/.cloudflared/cert.pem" ]]; then
  bold "Authorising against Cloudflare"
  echo "A browser will open. Choose $domain and authorise it."
  cloudflared tunnel login
fi

if cloudflared tunnel list --output json | grep -q "\"name\":\"$tunnel\""; then
  bold "Tunnel '$tunnel' already exists — reusing it"
else
  bold "Creating tunnel '$tunnel'"
  cloudflared tunnel create "$tunnel"
fi

uuid="$(cloudflared tunnel list --output json \
  | python3 -c 'import json,sys;print(next(t["id"] for t in json.load(sys.stdin) if t["name"]==sys.argv[1]))' "$tunnel")"
[[ -n "$uuid" ]] || fail "could not determine the UUID of tunnel '$tunnel'"

# The credentials file is the tunnel's private key — anything holding it can
# serve traffic as this tunnel. Copied next to the compose file rather than
# mounting a home directory into a container, and git-ignored.
#
# Readable by everyone on this machine, which looks wrong and is not. The
# cloudflared image runs as uid 65532, and a read-only bind mount does not remap
# ownership — so a 600 file owned by this user is simply unopenable inside the
# container, and the tunnel fails to register with no obvious cause (Cloudflare
# answers 1033, which reads like a network fault). The alternatives are worse:
# running the container as root, or chowning a file in the repository to a uid
# that means nothing on this machine.
creds_dir="deploy/cloudflared/creds"
creds="$creds_dir/$uuid.json"
mkdir -p "$creds_dir"
chmod 755 "$creds_dir"

if [[ -f "$creds" ]]; then
  bold "Credentials already in place"
elif [[ -f "$user_home/.cloudflared/$uuid.json" ]]; then
  bold "Copying credentials out of ~/.cloudflared"
  cp "$user_home/.cloudflared/$uuid.json" "$creds"
else
  # A fresh machine: the tunnel exists in Cloudflare, but its key was written on
  # the old one and is git-ignored, so it did not come with the clone. Reissued
  # rather than recreated — recreating would mint a new UUID and orphan all
  # seven DNS records, which is a five-minute outage for no reason.
  bold "Reissuing credentials for existing tunnel '$tunnel'"
  cloudflared tunnel token --cred-file "$creds" "$tunnel" \
    || fail "could not reissue credentials. Copy deploy/cloudflared/creds/$uuid.json from the old machine instead."
fi

chmod 644 "$creds"

# Paths here are the container's, not this machine's.
bold "Writing deploy/cloudflared/config.yml"
{
  echo "# Generated by scripts/tunnel-setup.sh. Re-run it rather than editing."
  echo "#"
  echo "# Every hostname lands on nginx, which does all the routing by Host header"
  echo "# exactly as it did before — the tunnel delivers traffic, it does not route."
  echo "# http, not https: that hop never leaves the Docker network, and the tunnel"
  echo "# has already encrypted everything that goes out to Cloudflare."
  echo "tunnel: $uuid"
  echo "credentials-file: /etc/cloudflared/creds/$uuid.json"
  echo "ingress:"
  for h in "${hostnames[@]}"; do
    echo "  - hostname: $h"
    echo "    service: http://nginx:80"
  done
  echo "  # Required last rule: anything not named above is refused rather than"
  echo "  # quietly handed to whatever happens to answer."
  echo "  - service: http_status:404"
} > deploy/cloudflared/config.yml

bold "Pointing DNS at the tunnel"
# Writes a proxied CNAME per name. Fails loudly if a conflicting record exists —
# usually a leftover A record from the port-forwarding attempt, which has to be
# deleted in the Cloudflare DNS tab by hand.
for h in "${hostnames[@]}"; do
  if cloudflared tunnel route dns "$tunnel" "$h" >/dev/null 2>&1; then
    printf '  %s\n' "$h"
  else
    warn "$h — record not created. Delete any existing A/CNAME for it in the Cloudflare DNS tab, then re-run."
  fi
done

bold "Next"
cat <<EOF
  ./scripts/up.sh          # starts the tunnel along with everything else

Then https://$domain — Cloudflare issues the certificate, so there is nothing to
do about TLS. Do not obtain a Let's Encrypt one for these names: nginx would
start redirecting to HTTPS, and the tunnel speaks HTTP to it. See
deploy/README.md.
EOF
